### Users Create Action
POST http://localhost:3000/users.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjI3NjkzMzV9.L2JNHfJXoOsyXTrDEugui4R-uwii9TqEOZBHNq9QBCw

{
  "name": "Willem",
  "email": "will@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Create Action
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "will@test.com",
  "password": "password"
}